### ISSUE TITLE
Heater / thermostat support?

### ISSUE THREAD

**Issue by blazer0x** [schemers/homebridge-screenlogic#1]
Thank you for creating this! I've got everything working including spa and pool temp display, but I seem to not be able to turn the heater on/off or adjust the pool or spa temperature.

**Comment by schemers** [comment]
Hi, glad it is working for you. I have yet to complete that functionality, they are listed in the [Other Potential HomeKit Accessory Types](https://github.com/schemers/homebridge-screenlogic#other-potential-homekit-accessory-types) section of the readme. 

There isn’t really a direct mapping to the standard HomeKit thermostat accessory, I was thinking of trying to it map it like so:

- Off -> Off
- Heat -> Heater
- Auto -> Solar Pref
- Cool -> Solar Only

If there is no solar present in the system Auto/Cool would probably just map to Off.

Seems like a reasonable mapping, though not perfect and potentially confusing to someone who doesn’t know the system, which is why I haven’t fully implemented (I also tend to just set and forget the heat, so just turning on the spa is enough for me).

**Comment by blazer0x** [comment]
I saw that and I guess I'm too n00b to figure out how to get it to work.
Your mapping idea seems fine, optimally I'd like to be able to say "turn the heater on/off", and of course "set the spa/pool temperature to X degrees". That would be REALLY nice for adjusting the temp while in the spa :) 

Do you have any way to send a donation? I'd like to contribute some thanks for your work on this project.

**Comment by schemers** [comment]
just released 1.3.1 which added "Pool Heater" and "Spa Heater" accessories. Mapping/caveats are described in README.md. 

Minimal testing, but seems to be working.

I was able to ask Siri to "set spa heater to 100" and it worked
